name: "Wait for checks"
description: "Wait for specific checks to complete"
author: tombl

branding:
  icon: check-square
  color: green

inputs:
  token:
    description: The GitHub token to use for authentication.
    default: ${{ github.token }}

  checks:
    description: |
      The names of the checks to wait for (comma separated).
      Each check is of the form `app-name/check-name` or `check-name`.
    required: true

  delay:
    description: How long to wait between checks
    default: 10s

  timeout:
    description: How long to wait before giving up
    default: 10m

outputs:
  statuses:
    description: The final status of each check

runs:
  using: node20
  main: bootstrap/main.mjs
