name: 'Deno example action'
description: 'An example of a Github Action written in Deno'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  # pre: bootstrap/pre.mjs
  main: bootstrap/main.mjs
  # post: bootstrap/post.mjs
