on:
  push:
  workflow_dispatch:

jobs:
  example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test local action
        uses: ./
        id: sleep
        with:
          milliseconds: 500

      - name: Print output
        run: echo "Slept until ${{ steps.sleep.outputs.time }}"
